default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_bots_dev

test:
  <<: *default
  database: my_bots_test

production:
  <<: *default
  database: my_bots_production
