development:
  secret_key_base: 833adb0382ab9244a3eb21cadbe874c79488dd2e1428201c2b7ecc195dff044130f09f0233ed9a56deebf11a8b6d2b89e9ffc7774b2b7305382856bcba775fab
  uber:
    client_id: <%= ENV["UBER_CLIENT_ID"] %>
    client_secret: <%= ENV["UBER_CLIENT_SECRET"] %>
    server_token: <%= ENV["UBER_SERVER_TOKEN"] %>
  messenger:
    verify_token: <%= ENV["MESSENGER_VERIFY_TOKEN"] %>
    page_access_token: <%= ENV["MESSENGER_PAGE_ACCESS_TOKEN"] %>
  domain_url: <%= ENV["DOMAIN_URL"] %>

test:
  secret_key_base: a803c61abb2b781b5f0d06356932b7cecc13b48091c7a896cb27fdeea625905dc86a452828246ca4ed3e0ded6e64c022dd493cd9f4df8f41f36b3d58b90d8a9b
  uber:
    client_id: <%= ENV["UBER_CLIENT_ID"] %>
    client_secret: <%= ENV["UBER_CLIENT_SECRET"] %>
    server_token: <%= ENV["UBER_SERVER_TOKEN"] %>
  messenger:
    verify_token: <%= ENV["MESSENGER_VERIFY_TOKEN"] %>
    page_access_token: <%= ENV["MESSENGER_PAGE_ACCESS_TOKEN"] %>
  domain_url: <%= ENV["DOMAIN_URL"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  uber:
    client_id: <%= ENV["UBER_CLIENT_ID"] %>
    client_secret: <%= ENV["UBER_CLIENT_SECRET"] %>
    server_token: <%= ENV["UBER_SERVER_TOKEN"] %>
  messenger:
    verify_token: <%= ENV["MESSENGER_VERIFY_TOKEN"] %>
    page_access_token: <%= ENV["MESSENGER_PAGE_ACCESS_TOKEN"] %>
  domain_url: <%= ENV["DOMAIN_URL"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
